schema_version = "1.0.0"

id = "io_import_build_map"
version = "1.3.3"
name = "BUILD Map Importer"
tagline = "Import BUILD Engine maps as used in Duke Nukem 3D, Blood, etc"
maintainer = "Jens Neitzel"
type = "add-on"

website = "https://github.com/jensnt/io_import_build_map"

tags = ["Import-Export", "Mesh", "Material"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2023 Jens Neitzel"]

[permissions]
files = "Import .map files and textures from filesystem"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/example/",
  "/images/",
]
